config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expense_categories, dependent: :destroy
  has_many :expenses, through: :expense_categories

  validates :name, presence: true
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id)
    @category_expenses = []

    @categories.each do |category|
      @category_expenses << category.expense_categories
    end
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @expense_category = ExpenseCategory.create(category: @category)

    respond_to do |format|
      if @category.save
        @category.expense_categories << @expense_category
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category_expenses_path(category.id) do %>
<div id="<%= dom_id category %>", class="bg-white px-5 py-3 flex items-center mb-5 hover:bg-[#3778c2] hover:text-white">
    <img class="w-1/4" src="<%= category.icon %>">
  <div class="flex flex-col">
    <p class="text-lg ml-4"><%= category.name %></p>
    <p class="text-sm ml-4">
    <strong>Total Expenses:</strong>
    $<%= category.expenses.reduce(0) {|sum, num| sum + num.amount} %>
    </p>
  </div>
</div>
<p class="hidden">
<%= link_to "Show this category", category %>
</p>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, class:"w-full") do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, class: "w-full py-1 pl-1 rounded-sm mb-5", placeholder: 'Name' %>
  </div>

  <div>
    <%= form.text_field :icon, class: "w-full py-1 pl-1 rounded-sm mb-5", placeholder: 'Icon' %>
  </div>

  <div class="invisible">
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="text-white text-center mt-10 bg-[#5fb523] w-full py-2 rounded-sm hover:bg-[#3778c2]" >
    <%= form.submit%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
  <div id="categories", class="mt-11 ">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>

  <%= link_to "New category", new_category_path, class:"text-white text-center mt-10 bg-[#5fb523] w-full py-2 rounded-sm mb-5 hover:bg-[#3778c2]" %>

app/views/categories/new.html.erb
<h1 class="mt-11 mb-11 text-lg self-start"><strong>NEW CATEGORY</strong></h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>