config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, dependent: :destroy
  has_many :categories

  validates :name, presence: true
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @category = Category.find(params[:category_id])
    @expenses = []
    @total = 0
    @category.expense_categories.order(created_at: :desc).each do |expense_category|
      @expenses.push(expense_category.expense)
      @total += expense_category.expense.amount
    end
  end

  # GET /expenses/1 or /expenses/1.json
  def show
    @category = Category.find(params[:category_id])
    @expenses = []
    @category.expenses.where(id: params[:id]).each do |expense_category|
      @expenses << expense_category
    end
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @param = params['format']
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = current_user.expenses.new(expense_params)

    respond_to do |format|
      if @expense.save
        ExpenseCategory.create(category_id: params[:category_id], expense_id: @expense.id)
        format.html do
          redirect_to category_expenses_path(params[:category_id]), notice: 'Expense was successfully created.'
        end
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html do
        redirect_to category_expenses_path(category_id: params[:category_id]),
                    notice: 'Expense was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, :user_id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<%= link_to category_expense_path(category_id: params[:category_id], id: expense.id) do %>
<div id="<%= dom_id expense %>", class="w-full bg-white px-5 py-3 flex flex-col mb-5 hover:bg-[#3778c2] hover:text-white">
<div class="flex justify-between text-lg">
  <p>
    <%= expense.name %>
  </p>

  <p>
    $<%= expense.amount %>
  </p>
</div>
    <p class="text-sm">
      Category: <% expense.categories.each do |category| %>
        <%=category.name%>
      <% end %>
    </p>
</div>
<% end %>

app/views/expenses/_form.html.erb
<%= form_with url: category_expenses_path(params[:category_id]), scope: :expense,  class:"w-full" do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, class: "w-full py-1 pl-1 rounded-sm mb-5", placeholder: 'Name' %>
  </div>

  <div>
    <%= form.text_field :amount, class: "w-full py-1 pl-1 rounded-sm mb-5", placeholder: 'Amount' %>
  </div>

  <div class="w-full hidden">
  <%= form.label :categories, style: "display: block" %>
  <% for category in Category.all %>
    <%= check_box_tag "expense[category_ids][]", category.id, expense.categories.include?(category)%>
    <%=h category.name%>
  <% end %>
  </div>

  <div class="invisible">
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div class="text-white text-center mt-10 bg-[#5fb523] w-full py-2 rounded-sm hover:bg-[#3778c2]">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", category_expense_path(category_id: params[:category_id], expense_id: params[:id]) %> |
  <%= link_to "Back to expenses", category_expenses_path(category_id: params[:category_id]) %>
</div>

app/views/expenses/index.html.erb
<h2 class="mb-11 mt-11 text-lg self-start"><strong>TOTAL EXPENSES:</strong> $<%=@total%> </h2>

<% if @expenses.empty? %>
  <h3>There aren't any expenses here yet</h3>
<% else %>
  <div id="expenses" class="w-full">
    <% @expenses.each do |expense| %>
      <%= render expense %>
    <% end %>
  </div>
<% end %>

<%= link_to "New expense", new_category_expense_path, class:"text-white text-center mt-10 bg-[#5fb523] w-full py-2 rounded-sm mb-5 hover:bg-[#3778c2]"%>

app/views/expenses/new.html.erb
<h1 class="my-11 text-lg self-start"><strong>NEW EXPENSE</strong></h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", category_expenses_path(params[:category_id]) %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="w-full mt-11 mb-5">
<% @expenses.each do |expense| %>
<%= render expense %>
<% end %>

  <%= link_to "Edit this expense", edit_category_expense_path(category_id: params[:category_id], expense_id: params[:id]), class:"hover:text-[#5fb523]" %>

  <%= button_to "Destroy this expense", category_expense_path(category_id: params[:category_id], expense_id: params[:id]), method: :delete, class:"text-white text-center mt-10 bg-[#5fb523] w-full py-2 rounded-sm hover:bg-[#3778c2]"%>
</div>